library(tidyverse)
library(GGally)
library(corrplot)
data("iris")
data=iris
dim(data)
attach(data)
tail(data)
str(data)
names(data)
summary(data)
ggplot(data,aes(x=Sepal.Length,y=Petal.Length,color=Species)) +geom_point()+theme_light()+ggtitle("Sepal vs Petal")
ggplot(data,aes(x=Sepal.Length,y=Petal.Length,color=Species,shape=Species)) +geom_point()+theme_light()+ggtitle("Sepal vs Petal")
ggplot(data,aes(x=Sepal.Length,y=Petal.Length,color=Species,shape=Species)) +geom_point()+theme_light()+geom_smooth()+ggtitle("Sepal vs Petal")
ggplot(data,aes(x=Sepal.Length,y=Petal.Length)) +geom_point(color="green")+theme_light()+geom_smooth(color="orange")+ggtitle("Sepal vs Petal")
ggplot(iris, aes(x=Sepal.Length, y=Petal.Length)) +geom_point(aes(col = Species)) +geom_smooth(se = FALSE)+theme_light()

data1=mtcars
attach(data1)
ggplot(data1, aes(hp, mpg)) + geom_point(color = "orange") + stat_summary(fun.y = "mean", geom = "line", linetype = "dashed")
ggplot(data1,aes(gear))+geom_bar(color="red")+theme_light()
ggplot(data1,aes(gear))+geom_bar(color="red")+theme_light()+coord_flip()
ggplot(mtcars,aes(as.factor(cyl),mpg))+geom_boxplot(color=2)+theme_light()
data1$cyl <- as.factor(data1$cyl)
ggplot(data1,aes(cyl,mpg,fill=cyl))+geom_boxplot()+scale_fill_manual(values = c("orange",2,3))
ggplot(data1,aes(cyl,mpg))+geom_violin(aes(fill=cyl))+theme_classic()
ggplot(data1,aes(x="",y=mpg,fill=cyl))+geom_bar(stat="identity",width = 1)+ coord_polar("y",start=0) + theme_classic()
ggpairs(data1)
ggpairs(data1,columns = 1:4,aes(color=cyl,alpha=0.5))
ggplot(data1,aes(mpg,hp))+geom_density_2d_filled(show.legend = F)+coord_cartesian(expand = F)+labs(x="mpg")
ggplot(data1,aes(x=mpg,y=hp))+geom_point()+geom_density_2d()
corr <- round(cor(mtcars),1)
corrplot(corr, method="circle")
corrplot(corr, method="color")
corrplot(corr, method="number")
corrplot(corr, type="upper", order="hclust", tl.col="black", tl.srt=45)



set.seed(123)
x<-rnorm(1000)
y<-rnorm(1000,2)
X<-c(x,y)
G<-c(rep("G1",1000),rep("G2",1000))
df<-data.frame(X,group=G)
ggplot(df,aes(X,fill=G))+geom_histogram(bins = 30,position = "identity")
ggplot(df, aes(x = X, fill = group)) + geom_histogram(bins=30,color = 1, alpha = 0.70,position = "identity") +scale_fill_manual(values = c("#ff4d6d", "#c77dff"))+theme_light()


